### ISSUE TITLE
Deck 0.6.1 missing plugin creation

### ISSUE THREAD

**Issue by cello86** [hbagdi/deck#104]
Hi,
I'm trying to use the newer version of Deck and the routes and services are created correctly but I noticed that the plugins are missing in the sync action. I just created this example yaml file:

```
_format_version: "1.1"
_workspace: myworkspace-dev
services:
- connect_timeout: 60000
  host: localhost
  name: kong-localinstance
  path: /
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - hosts:
    - "localhost"
    name: kong-internal-probe
    methods:
    - GET
    paths:
    - /kong-probe.html
    preserve_host: false
    protocols:
    - http
    regex_priority: 0
    strip_path: false
    plugins:
    - name: request-termination
      config:
        body: Kong localhost probe
        content_type: application/json; charset=utf-8
        message: Kong localhost probe
        status_code: 200
      enabled: true
      run_on: first
```

Into the Kong EE 0.35_3 admin instance I noticed these API requests:

```
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /workspaces/myworkspace-dev HTTP/1.1" 200 662 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/services?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/routes?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/plugins?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/certificates?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/ca_certificates?size=1000 HTTP/1.1" 404 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/snis?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/upstreams?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/consumers?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:36 +0100] "GET /myworkspace-dev/key-auths?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "GET /myworkspace-dev/hmac-auths?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "GET /myworkspace-dev/jwts?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "GET /myworkspace-dev/basic-auths?size=1000 HTTP/1.1" 200 3468 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "GET /myworkspace-dev/oauth2?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "GET /myworkspace-dev/acls?size=1000 HTTP/1.1" 200 23 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "PUT /myworkspace-dev/services/b84d4058-7444-434e-a176-48dfba2189f4 HTTP/1.1" 200 259 "-" "Go-http-client/1.1"
127.0.0.1 - - [11/Nov/2019:11:46:37 +0100] "PUT /myworkspace-dev/routes/18e18b47-39aa-43ca-b134-e8ab0d059fac HTTP/1.1" 200 376 "-" "Go-http-client/1.1"
```

The PUT action for the plugin hasn't been performed and I tried to populate for the plugin part to avoid this issue #77 without success.

Marcello
