### ISSUE TITLE
bug: select_tags also tags non-taggable resources

### ISSUE THREAD

**Issue by raittes** [hbagdi/deck#114]
Creating some consumer with an jwt_secret using `select_tags`  
results in the `tags` being set for the `jwt_secrets`,  that does not support tags.
Version: `decK v0.7.0 (69bdff4)`

```
# consumer.yaml
format_version: "1.1"
_info:
  select_tags:
  - sometag
consumers:
- username: someuser
  jwt_secrets:
  - algorithm: HS256
    key: somekey
    secret: somesecret
```

Results in:
```
deck sync -s consumer.yaml
creating consumer someuser
creating jwt-auth somekey for consumer 4a79914d-669f-4155-9d04-631396989bf1
Error: 1 errors occurred:
	while processing event: {Create} failed: 400 Bad Request
{
  "message":"schema violation (tags: unknown field)",
  "name":"schema violation",
  "fields":{"tags":"unknown field"},
  "code":2
}
```

Same error for resources: KeyAuths, BasicAuths, HMACAuths, JWTAuths, Oauth2Creds, ACLGroups
