### ISSUE TITLE
Configuration Export has some parsing errors

### ISSUE THREAD

**Issue by surfer190** [hbagdi/deck#14]
After doing a `deck dump` and then running a `kong config parse kong.yaml` it has showns a few discrepencies:

1. No `'_format_version':` - needed at the top of the file
2. A null value was added for an empty field:

```
  plugins:
  - name: request-transformer
    config:
      add:
        body: []
        headers: []
        querystring:
        - fmt:json
        - period:d
      append:
        body: []
        headers: []
        querystring: []
      http_method: null
```
