### ISSUE TITLE
feature: interpolated state like docker-compose

### ISSUE THREAD

**Issue by eamonnmcevoy** [hbagdi/deck#62]
It would be useful if we could pass multiple state files in a specific order, and override individual values in the same way that docker compose supports. 

for reference: https://docs.docker.com/compose/extends/#understanding-multiple-compose-files

If I have a production state yaml file, I may want to override an individual value for development, experimenting with a new feature.

Lets say I have the following state file:

kong.yaml
```
services:
- name: svc1
  host: my-api:8080
  routes:
  - name: r1
    paths:
    - /r1
      plugins:
      - name: jwt
        config:
          secret_is_base64: false
          key_claim_name: iss
          claims_to_verify:
          - exp
          cookie_names:
          - auth_jwt
          anonymous: null
          run_on_preflight: true
```

Example scenario 1:
I want to set an anonymous user for use in local development/testing

kong.local.yaml
```
services:
- name: svc1
  routes:
  - name: r1
      plugins:
      - name: jwt
        config:
          anonymous: bc92eeda-c35b-11e9-9cb5-2a2ae2dbcce4
```

`deck sync --kong-addr="http://kong:8001" -s=kong.yaml -s=kong.local.yaml`

In this case I would expect the value of anonymous in route r1 to be 'bc92eeda-c35b-11e9-9cb5-2a2ae2dbcce4'.

Example scenario 2:
I want to include an additional route with debug logs on my development environment

kong.dev.yaml
```
services:
- name: svc1
  routes:
  - name: r1-debug
    paths:
    - /debug/r1
      plugins:
      - name: file-log
        config:
          path: /tmp/file.log
      - name: jwt
        config:
          secret_is_base64: false
          key_claim_name: iss
          claims_to_verify:
          - exp
          cookie_names:
          - auth_jwt
          anonymous: null
          run_on_preflight: true
```

`deck sync --kong-addr="http://kong:8001" -s=kong.yaml -s=kong.dev.yaml`

In this case I would expect a new route to be added to svc1.
