### ISSUE TITLE
How to handle the anonymous field on auth plugins

### ISSUE THREAD

**Issue by eamonnmcevoy** [hbagdi/deck#69]
If I want to configure the anonymous field on a jwt plugin, is there a way to handle this in deck?

Its tricky because this field requires the consumer id, which we cannot know until the consumer has been created already.

It would be useful if we could set this field using 'username' in deck, and to have the ability to list some users in the config so that deck will ensure they exist, even when the --skip-consumers flag is used (or maybe have another flag to enable this). 

Update:

I see that using the kong admin api I can create a consumer and specify the id so i guess that part should be possible to get working in deck

As for the issue of synching only certain consumers, I have 2 suggestions. 
1) include a parameter to only create consumers and ignore updates or deletions `--create-consumers`
2) alternatively, a flag to sync consumers with a particular tag(s). For example, `--sync-consumer-tags=anonymous` will perform synchronize actions on users with the `anonymous` tag and ignore others.

**Comment by hbagdi** [comment]
> As for the issue of synching only certain consumers, I have 2 suggestions.

This is a very common issue that comes up far too often and decK has concept of `select-tags`.

You can configure decK to perform a sync/diff only for a sub-set of entire Kong configuration.

Please take a look at: https://github.com/hbagdi/deck/blob/master/kong.yaml#L2

You can then manage only a subset of consumers of plugins or any entity you would like.
With this, you can have a state file to manage a single anonymous consumer.
And then the other state file can manage rest of the configuration.

**Comment by eamonnmcevoy** [comment]
Perfect, `select-tags` does the trick.

For the anonymous user id, what do you think about decK setting the consumer id directly?
An alternative approach could be to have a new tag that acts like a function to fetch a consumerid based on the consumer username:

```
_info:
  select_tags:
  - managed_by_deck

services:

  - name: service1
    host: httpbin.org
    path: /
    protocol: http
    port: 80
    connect_timeout: 60000
    read_timeout: 60000
    write_timeout: 60000
    retries: 5
    tags:
    - managed_by_deck
    routes:
    - name: service1_route1
      paths:
      - /
      preserve-host: false
      methods:
      - GET
      protocols:
      - http
      - https
      regex_priority: 0
      strip_path: true
      tags:
      - managed_by_deck
      plugins:
      - name: key-auth
        tags:
        - managed_by_deck
        config:
          anonymous: _consumer_id(anonymous)

consumers:
- username: anonymous
  custom_id: anonymous
  tags:
  - managed_by_deck
  
```
