### ISSUE TITLE
Null Http method Issue

### ISSUE THREAD

**Issue by surfer190** [hbagdi/deck#71]
After exporting my config from `1.1.0` with the `deck 1.5.1` I get the following error when importing it on kong `1.3.1`:

```
in 'services':
  - in entry 1 of 'services':
    in 'plugins':
      - in entry 1 of 'plugins':
        in 'config':
          in 'http_method': expected a string
```

Snippet of my config:

```
_format_version: "1.1"
services:
- connect_timeout: 60000
  host: example.com
  name: eod_historical_data
  path: /api/
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - hosts:
    - api.example.com
    name: real-time
    paths:
    - /real-time
    preserve_host: false
    protocols:
    - https
    regex_priority: 0
    strip_path: false
  plugins:
  - name: request-transformer
    config:
      add:
        body: []
        headers: []
        querystring:
        - api_token:abc
        - fmt:json
      append:
        body: []
        headers: []
        querystring: []
      http_method: null
```
