### ISSUE TITLE
Empty plugin fields should be skipped

### ISSUE THREAD

**Issue by hbagdi** [hbagdi/deck#77]
decK currently exports plugin configuration with all fields set as `null`, as returned by Kong's Admin API:
```
plugins:
- name: cors
    config:
    credentials: false
    exposed_headers: null
    headers: null
    max_age: null
```

However, Kong will roar out loud if you give it back the same representation, because schema validations fail and `headers` cannot be `null`.

To work around this, upon exporting configuration, recursively remove `null` fields from the configuration and then export the configuration.

See #56
